### ISSUE TITLE
Add atleast one tool

### ISSUE THREAD

**Issue by Lufffya** [TransformerOptimus/SuperAGI#192]
I use the Docker command (`docker-compose up --build`) to run on the latest code

Always prompt `Add atleast one tool` when creating a agent

**Comment by Lufffya** [comment]
docker-compose logs:
```
superagi-celery-1  | Connected to the database! @ postgresql://superagi:password@super__postgres/super_agi_main
superagi-celery-1  | /usr/local/lib/python3.9/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
superagi-backend-1  | wait-for-it.sh: waiting 60 seconds for super__postgres:5432
superagi-backend-1  | wait-for-it.sh: super__postgres:5432 is available after 0 seconds
superagi-backend-1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
superagi-celery-1   | absolutely not recommended!
superagi-celery-1   | 
superagi-super__postgres-1  | The files belonging to this database system will be owned by user "postgres".
superagi-super__postgres-1  | This user must also own the server process.
superagi-super__postgres-1  | 
superagi-super__postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
superagi-celery-1           | Please specify a different user using the --uid option.
superagi-super__redis-1     | 1:C 06 Jun 2023 02:29:27.495 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
superagi-super__redis-1     | 1:C 06 Jun 2023 02:29:27.495 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
superagi-super__redis-1     | 1:C 06 Jun 2023 02:29:27.495 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
superagi-super__redis-1     | 1:M 06 Jun 2023 02:29:27.496 * monotonic clock: POSIX clock_gettime
superagi-celery-1           | 
superagi-celery-1           | User information: uid=0 euid=0 gid=0 egid=0
superagi-super__redis-1     | 1:M 06 Jun 2023 02:29:27.497 * Running mode=standalone, port=6379.
superagi-super__redis-1     | 1:M 06 Jun 2023 02:29:27.497 # Server initialized
superagi-super__postgres-1  | The default database encoding has accordingly been set to "UTF8".
superagi-super__postgres-1  | The default text search configuration will be set to "english".
superagi-super__postgres-1  | 
superagi-super__redis-1     | 1:M 06 Jun 2023 02:29:27.497 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
superagi-gui-1              | 
superagi-super__postgres-1  | Data page checksums are disabled.
superagi-gui-1              | > super-agi@0.1.0 dev
superagi-gui-1              | > next dev
superagi-gui-1              | 
superagi-gui-1              | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
superagi-celery-1           | 
superagi-celery-1           |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
superagi-celery-1           |  
superagi-celery-1           |  -------------- celery@0590368684cf v5.2.7 (dawn-chorus)
superagi-celery-1           | --- ***** ----- 
superagi-celery-1           | -- ******* ---- Linux-5.15.0-73-generic-x86_64-with-glibc2.31 2023-06-06 03:24:21
superagi-celery-1           | - *** --- * --- 
superagi-super__postgres-1  | 
superagi-super__redis-1     | 1:M 06 Jun 2023 02:29:27.498 * Ready to accept connections
superagi-super__postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
superagi-celery-1           | - ** ---------- [config]
superagi-super__postgres-1  | creating subdirectories ... ok
superagi-celery-1           | - ** ---------- .> app:         superagi:0x7f078b956fd0
superagi-backend-1          | INFO  [alembic.runtime.migration] Will assume transactional DDL.
superagi-backend-1          | INFO:     Will watch for changes in these directories: ['/app']
superagi-super__redis-1     | 1:signal-handler (1686021667) Received SIGTERM scheduling shutdown...
superagi-super__redis-1     | 1:M 06 Jun 2023 03:21:07.534 # User requested shutdown...
superagi-super__redis-1     | 1:M 06 Jun 2023 03:21:07.534 * Saving the final RDB snapshot before exiting.
superagi-backend-1          | INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
superagi-backend-1          | INFO:     Started reloader process [1] using WatchFiles
superagi-backend-1          | Connected to the database! @ postgresql://superagi:password@super__postgres/super_agi_main
superagi-backend-1          | INFO:     Started server process [20]
superagi-backend-1          | INFO:     Waiting for application startup.
superagi-backend-1          | INFO:     Application startup complete.
superagi-super__redis-1     | 1:M 06 Jun 2023 03:21:07.540 * DB saved on disk
superagi-super__redis-1     | 1:M 06 Jun 2023 03:21:07.540 # Redis is now ready to exit, bye bye...
superagi-super__redis-1     | 1:C 06 Jun 2023 03:24:18.232 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
superagi-super__redis-1     | 1:C 06 Jun 2023 03:24:18.232 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
superagi-super__redis-1     | 1:C 06 Jun 2023 03:24:18.232 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.232 * monotonic clock: POSIX clock_gettime
superagi-backend-1          | INFO:     172.18.0.1:51706 - "OPTIONS /users/add HTTP/1.1" 400 Bad Request
superagi-celery-1           | - ** ---------- .> transport:   redis://super__redis:6379/0
superagi-backend-1          | INFO:     172.18.0.1:51702 - "GET /agents/get/project/ HTTP/1.1" 307 Temporary Redirect
superagi-gui-1              | - warn Invalid next.config.js options detected: 
superagi-celery-1           | - ** ---------- .> results:     redis://super__redis:6379/0
superagi-celery-1           | - *** --- * --- .> concurrency: 10 (prefork)
superagi-celery-1           | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
superagi-gui-1              | - warn     The root value has an unexpected property, webpackDevMiddleware, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, configOrigin, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, target, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
superagi-gui-1              | - warn See more info here: https://nextjs.org/docs/messages/invalid-next-config
superagi-celery-1           | --- ***** ----- 
superagi-celery-1           |  -------------- [queues]
superagi-celery-1           |                 .> celery           exchange=celery(direct) key=celery
superagi-celery-1           |                 
superagi-celery-1           | 
superagi-celery-1           | [tasks]
superagi-super__postgres-1  | selecting dynamic shared memory implementation ... posix
superagi-super__postgres-1  | selecting default max_connections ... 100
superagi-super__postgres-1  | selecting default shared_buffers ... 128MB
superagi-super__postgres-1  | selecting default time zone ... Etc/UTC
superagi-super__postgres-1  | creating configuration files ... ok
superagi-super__postgres-1  | running bootstrap script ... ok
superagi-super__postgres-1  | performing post-bootstrap initialization ... ok
superagi-super__postgres-1  | syncing data to disk ... ok
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.233 * Running mode=standalone, port=6379.
superagi-celery-1           |   . execute_agent
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.233 # Server initialized
superagi-celery-1           | 
superagi-celery-1           | [2023-06-06 03:24:22,225: INFO/MainProcess] Connected to redis://super__redis:6379/0
superagi-celery-1           | [2023-06-06 03:24:22,230: INFO/MainProcess] mingle: searching for neighbors
superagi-celery-1           | [2023-06-06 03:24:23,240: INFO/MainProcess] mingle: all alone
superagi-gui-1              | - event compiled client and server successfully in 1750 ms (775 modules)
superagi-gui-1              | - wait compiling...
superagi-celery-1           | [2023-06-06 03:24:23,253: INFO/MainProcess] celery@0590368684cf ready.
superagi-super__postgres-1  | 
superagi-super__postgres-1  | 
superagi-super__postgres-1  | Success. You can now start the database server using:
superagi-gui-1              | - event compiled client and server successfully in 613 ms (775 modules)
superagi-gui-1              | - wait compiling /_error (client and server)...
superagi-gui-1              | - event compiled client and server successfully in 256 ms (776 modules)
superagi-gui-1              | Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"). Use Document instead. 
superagi-gui-1              | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
superagi-gui-1              | - wait compiling /favicon.ico/route (client and server)...
superagi-gui-1              | - event compiled successfully in 115 ms (132 modules)
superagi-super__postgres-1  | 
superagi-super__postgres-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
superagi-super__postgres-1  | 
superagi-super__postgres-1  | initdb: warning: enabling "trust" authentication for local connections
superagi-super__postgres-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
superagi-backend-1          | INFO:     172.18.0.1:51686 - "GET /tools/get HTTP/1.1" 200 OK
superagi-super__postgres-1  | waiting for server to start....2023-06-06 02:29:28.415 UTC [48] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
superagi-backend-1          | INFO:     172.18.0.1:51714 - "GET /projects/get/organisation/1 HTTP/1.1" 200 OK
superagi-backend-1          | INFO:     172.18.0.1:51690 - "GET /organisations/get/1 HTTP/1.1" 200 OK
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.233 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.234 * Loading RDB produced by version 7.0.11
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.234 * RDB age 191 seconds
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.234 * RDB memory usage when created 1.18 Mb
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.234 * Done loading RDB, keys loaded: 1, keys expired: 0.
superagi-super__postgres-1  | 2023-06-06 02:29:28.417 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superagi-super__postgres-1  | 2023-06-06 02:29:28.423 UTC [51] LOG:  database system was shut down at 2023-06-06 02:29:28 UTC
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.234 * DB loaded from disk: 0.000 seconds
superagi-super__redis-1     | 1:M 06 Jun 2023 03:24:18.234 * Ready to accept connections
superagi-super__postgres-1  | 2023-06-06 02:29:28.429 UTC [48] LOG:  database system is ready to accept connections
superagi-super__postgres-1  |  done
superagi-super__postgres-1  | server started
superagi-super__postgres-1  | CREATE DATABASE
superagi-super__postgres-1  | 
superagi-super__postgres-1  | 
superagi-super__postgres-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
superagi-super__postgres-1  | 
superagi-super__postgres-1  | 2023-06-06 02:29:28.643 UTC [48] LOG:  received fast shutdown request
superagi-super__postgres-1  | waiting for server to shut down....2023-06-06 02:29:28.645 UTC [48] LOG:  aborting any active transactions
superagi-super__postgres-1  | 2023-06-06 02:29:28.646 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
superagi-super__postgres-1  | 2023-06-06 02:29:28.647 UTC [49] LOG:  shutting down
superagi-super__postgres-1  | 2023-06-06 02:29:28.649 UTC [49] LOG:  checkpoint starting: shutdown immediate
superagi-super__postgres-1  | 2023-06-06 02:29:28.692 UTC [49] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.022 s, sync=0.015 s, total=0.045 s; sync files=250, longest=0.002 s, average=0.001 s; distance=4217 kB, estimate=4217 kB
superagi-super__postgres-1  | 2023-06-06 02:29:28.698 UTC [48] LOG:  database system is shut down
superagi-super__postgres-1  |  done
superagi-super__postgres-1  | server stopped
superagi-super__postgres-1  | 
superagi-super__postgres-1  | PostgreSQL init process complete; ready for start up.
superagi-super__postgres-1  | 
superagi-super__postgres-1  | 2023-06-06 02:29:28.770 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
superagi-super__postgres-1  | 2023-06-06 02:29:28.770 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
superagi-super__postgres-1  | 2023-06-06 02:29:28.771 UTC [1] LOG:  listening on IPv6 address "::", port 5432
superagi-super__postgres-1  | 2023-06-06 02:29:28.774 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superagi-super__postgres-1  | 2023-06-06 02:29:28.780 UTC [64] LOG:  database system was shut down at 2023-06-06 02:29:28 UTC
superagi-super__postgres-1  | 2023-06-06 02:29:28.786 UTC [1] LOG:  database system is ready to accept connections
superagi-super__postgres-1  | 2023-06-06 02:34:28.880 UTC [62] LOG:  checkpoint starting: time
superagi-super__postgres-1  | 2023-06-06 02:34:45.048 UTC [62] LOG:  checkpoint complete: wrote 164 buffers (1.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=16.149 s, sync=0.008 s, total=16.169 s; sync files=75, longest=0.002 s, average=0.001 s; distance=760 kB, estimate=760 kB
superagi-super__postgres-1  | 2023-06-06 03:21:07.490 UTC [1] LOG:  received fast shutdown request
superagi-super__postgres-1  | 2023-06-06 03:21:07.492 UTC [1] LOG:  aborting any active transactions
superagi-super__postgres-1  | 2023-06-06 03:21:07.494 UTC [1] LOG:  background worker "logical replication launcher" (PID 67) exited with exit code 1
superagi-super__postgres-1  | 2023-06-06 03:21:07.495 UTC [62] LOG:  shutting down
superagi-super__postgres-1  | 2023-06-06 03:21:07.497 UTC [62] LOG:  checkpoint starting: shutdown immediate
superagi-super__postgres-1  | 2023-06-06 03:21:07.505 UTC [62] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.010 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=684 kB
superagi-super__postgres-1  | 2023-06-06 03:21:07.514 UTC [1] LOG:  database system is shut down
superagi-super__postgres-1  | 
superagi-super__postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
superagi-super__postgres-1  | 
superagi-super__postgres-1  | 2023-06-06 03:24:18.291 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
superagi-super__postgres-1  | 2023-06-06 03:24:18.299 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
superagi-super__postgres-1  | 2023-06-06 03:24:18.299 UTC [1] LOG:  listening on IPv6 address "::", port 5432
superagi-super__postgres-1  | 2023-06-06 03:24:18.303 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superagi-super__postgres-1  | 2023-06-06 03:24:18.311 UTC [29] LOG:  database system was shut down at 2023-06-06 03:21:07 UTC
superagi-super__postgres-1  | 2023-06-06 03:24:18.320 UTC [1] LOG:  database system is ready to accept connections
superagi-super__postgres-1  | 2023-06-06 03:29:18.410 UTC [27] LOG:  checkpoint starting: time
superagi-super__postgres-1  | 2023-06-06 03:29:18.731 UTC [27] LOG:  checkpoint complete: wrote 6 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.305 s, sync=0.006 s, total=0.321 s; sync files=5, longest=0.005 s, average=0.002 s; distance=4 kB, estimate=4 kB
```

**Comment by sonu4sam** [comment]
PS C:\Users\Sourav\Desktop\SuperAGI> docker-compose up --build
2023/06/05 22:32:49 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 1.4s (32/32) FINISHED
 => [celery internal] load build definition from DockerfileCelery                                                                                            0.0s
 => => transferring dockerfile: 259B                                                                                                                         0.0s 
 => [celery internal] load .dockerignore                                                                                                                     0.0s 
 => => transferring context: 51B                                                                                                                             0.0s 
 => [celery internal] load metadata for docker.io/library/python:3.9                                                                                         0.7s
 => [gui internal] load build definition from Dockerfile                                                                                                     0.0s 
 => => transferring dockerfile: 149B                                                                                                                         0.0s 
 => [gui internal] load .dockerignore                                                                                                                        0.0s 
 => => transferring context: 2B                                                                                                                              0.0s 
 => [gui internal] load metadata for docker.io/library/node:lts                                                                                              0.7s 
 => [backend internal] load build definition from Dockerfile                                                                                                 0.0s 
 => => transferring dockerfile: 387B                                                                                                                         0.0s 
 => [backend internal] load .dockerignore                                                                                                                    0.0s 
 => => transferring context: 51B                                                                                                                             0.0s 
 => [gui 1/5] FROM docker.io/library/node:lts@sha256:8cdf7234449f35e579f7491137807ddb3a089f028862f7ab69af437cc9f47ff1                                        0.0s
 => [gui internal] load build context                                                                                                                        0.0s 
 => => transferring context: 4.48kB                                                                                                                          0.0s 
 => [backend 1/9] FROM docker.io/library/python:3.9@sha256:603ac689b89c2a59791a4e7cd3d727f2a673ac3df02dabbd97b0d85bb1eca4e7                                  0.0s
 => [backend internal] load build context                                                                                                                    0.1s 
 => => transferring context: 107.73kB                                                                                                                        0.1s 
 => [celery internal] load build context                                                                                                                     0.1s 
 => => transferring context: 107.73kB                                                                                                                        0.1s 
 => CACHED [gui 2/5] WORKDIR /app                                                                                                                            0.0s 
 => CACHED [gui 3/5] COPY package*.json ./                                                                                                                   0.0s 
 => CACHED [gui 4/5] RUN npm install                                                                                                                         0.0s 
 => [gui 5/5] COPY . .                                                                                                                                       0.1s 
 => CACHED [backend 2/9] WORKDIR /app                                                                                                                        0.0s 
 => CACHED [celery 3/6] COPY requirements.txt .                                                                                                              0.0s 
 => CACHED [celery 4/6] RUN pip install --no-cache-dir -r requirements.txt                                                                                   0.0s
 => [celery 5/6] COPY . .                                                                                                                                    0.1s 
 => [gui] exporting to image                                                                                                                                 0.0s 
 => => exporting layers                                                                                                                                      0.0s 
 => => writing image sha256:9f9cee65598a1efe0eb6451aa7579fc00d07e3cf799bf1e4ff76e9522160d835                                                                 0.0s 
 => => naming to docker.io/library/superagi-gui                                                                                                              0.0s 
 => CACHED [backend 3/9] COPY requirements.txt .                                                                                                             0.0s 
 => CACHED [backend 4/9] RUN pip install --no-cache-dir -r requirements.txt                                                                                  0.0s 
 => CACHED [backend 5/9] COPY . .                                                                                                                            0.0s 
 => [backend 6/9] COPY config.yaml ./config.yaml                                                                                                             0.0s 
 => [celery 6/6] COPY config.yaml .                                                                                                                          0.0s 
 => [backend 7/9] COPY entrypoint.sh /entrypoint.sh                                                                                                          0.0s 
 => [celery] exporting to image                                                                                                                              0.1s 
 => => exporting layers                                                                                                                                      0.1s 
 => => writing image sha256:2a253f9382634298f4696ac0cc0042d33c4fffcff259f2933bd2eced9c0aaad4                                                                 0.0s 
 => => naming to docker.io/library/superagi-celery                                                                                                           0.0s 
 => [backend 8/9] COPY wait-for-it.sh /wait-for-it.sh                                                                                                        0.0s 
 => [backend 9/9] RUN chmod +x /entrypoint.sh /wait-for-it.sh                                                                                                0.4s 
 => [backend] exporting to image                                                                                                                             0.0s 
 => => exporting layers                                                                                                                                      0.0s 
 => => writing image sha256:fda33af9bd96f940a08afcc81e8ff3d0d9fc20a6a9cc8116ee732e9b4fd05a80                                                                 0.0s 
 => => naming to docker.io/library/superagi-backend                                                                                                          0.0s 
[+] Running 5/5
 ✔ Container superagi-super__redis-1     Created                                                                                                             0.0s 
 ✔ Container superagi-super__postgres-1  Created                                                                                                             0.0s 
 ✔ Container superagi-gui-1              Recreated                                                                                                           0.1s 
 ✔ Container superagi-celery-1           Recreated                                                                                                           0.1s 
 ✔ Container superagi-backend-1          Recreated                                                                                                           0.1s 
Attaching to superagi-backend-1, superagi-celery-1, superagi-gui-1, superagi-super__postgres-1, superagi-super__redis-1
superagi-super__postgres-1  | 
superagi-super__postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
superagi-super__postgres-1  |
superagi-super__postgres-1  | 2023-06-06 03:32:51.756 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
superagi-super__postgres-1  | 2023-06-06 03:32:51.777 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
superagi-super__postgres-1  | 2023-06-06 03:32:51.778 UTC [1] LOG:  listening on IPv6 address "::", port 5432
superagi-super__postgres-1  | 2023-06-06 03:32:51.781 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superagi-super__redis-1     | 1:C 06 Jun 2023 03:32:51.782 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
superagi-super__redis-1     | 1:C 06 Jun 2023 03:32:51.782 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
superagi-super__redis-1     | 1:C 06 Jun 2023 03:32:51.782 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.782 * monotonic clock: POSIX clock_gettime
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.783 * Running mode=standalone, port=6379.
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.783 # Server initialized
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.783 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.784 * Loading RDB produced by version 7.0.11
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.784 * RDB age 25 seconds
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.784 * RDB memory usage when created 1.18 Mb
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.786 * Done loading RDB, keys loaded: 1, keys expired: 0.
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.786 * DB loaded from disk: 0.002 seconds
superagi-super__redis-1     | 1:M 06 Jun 2023 03:32:51.786 * Ready to accept connections
superagi-super__postgres-1  | 2023-06-06 03:32:51.793 UTC [29] LOG:  database system was shut down at 2023-06-06 03:32:26 UTC
superagi-super__postgres-1  | 2023-06-06 03:32:51.800 UTC [1] LOG:  database system is ready to accept connections
superagi-gui-1              | 
superagi-gui-1              | > super-agi@0.1.0 dev
superagi-gui-1              | > next dev
superagi-gui-1              |
superagi-backend-1          | /usr/bin/env: ‘bash\r’: No such file or directory
superagi-gui-1              | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
superagi-gui-1              | - warn Invalid next.config.js options detected: 
superagi-gui-1              | - warn     The root value has an unexpected property, webpackDevMiddleware, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, configOrigin, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, target, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
superagi-gui-1              | - warn See more info here: https://nextjs.org/docs/messages/invalid-next-config
superagi-celery-1           | Connected to the database! @ postgresql://superagi:password@super__postgres/super_agi_main
superagi-gui-1              | - event compiled client and server successfully in 3.5s (775 modules)
superagi-gui-1              | - wait compiling...
superagi-celery-1           | /usr/local/lib/python3.9/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
superagi-celery-1           | absolutely not recommended!
superagi-celery-1           |
superagi-celery-1           | Please specify a different user using the --uid option.
superagi-celery-1           |
superagi-celery-1           | User information: uid=0 euid=0 gid=0 egid=0
superagi-celery-1           |
superagi-celery-1           |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
superagi-celery-1           |  
superagi-celery-1           |  -------------- celery@993c2d5337c4 v5.2.7 (dawn-chorus)
superagi-celery-1           | --- ***** -----
superagi-celery-1           | -- ******* ---- Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31 2023-06-06 03:32:59
superagi-celery-1           | - *** --- * ---
superagi-celery-1           | - ** ---------- [config]
superagi-celery-1           | - ** ---------- .> app:         superagi:0x7f3b42e98040
superagi-celery-1           | - ** ---------- .> transport:   redis://super__redis:6379/0
superagi-celery-1           | - ** ---------- .> results:     redis://super__redis:6379/0
superagi-celery-1           | - *** --- * --- .> concurrency: 10 (prefork)
superagi-celery-1           | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
superagi-celery-1           | --- ***** -----
superagi-celery-1           |  -------------- [queues]
superagi-celery-1           |                 .> celery           exchange=celery(direct) key=celery
superagi-celery-1           |
superagi-celery-1           |
superagi-celery-1           | [tasks]
superagi-celery-1           |   . execute_agent
superagi-celery-1           | 
superagi-backend-1 exited with code 127
superagi-gui-1              | - event compiled client and server successfully in 7.3s (775 modules)
superagi-celery-1           | [2023-06-06 03:33:07,368: INFO/MainProcess] Connected to redis://super__redis:6379/0
superagi-celery-1           | [2023-06-06 03:33:07,373: INFO/MainProcess] mingle: searching for neighbors
superagi-celery-1           | [2023-06-06 03:33:08,389: INFO/MainProcess] mingle: all alone
superagi-celery-1           | [2023-06-06 03:33:08,405: INFO/MainProcess] celery@993c2d5337c4 ready.
superagi-gui-1              | - wait compiling /_error (client and server)...
superagi-gui-1              | - event compiled client and server successfully in 654 ms (776 modules)
superagi-gui-1              | Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"). Use Document instead.
superagi-gui-1              | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
superagi-gui-1              | - wait compiling /favicon.ico/route (client and server)...
superagi-gui-1              | - event compiled successfully in 109 ms (132 modules)

**Comment by sonu4sam** [comment]
the same problem, says that add at least one tool, and no provisions to add tools.

**Comment by LCASUSA** [comment]
im having the same issue

**Comment by MatheusMeM** [comment]
Same issue here, bummer

**Comment by fcodag** [comment]
check #160, seems to be the right solution for Windows

**Comment by MatheusMeM** [comment]
Quoting another user in #Issues 

"For windows check https://github.com/TransformerOptimus/SuperAGI/issues/160

it helped me.

Quickly:

Open files entrypoint.sh and wait-for-it.sh in Visual Studio Code.

For each of them:

in vscode at bottom right check for CLRF
if it is CLRF then click on it and change it to LF

Save it

Delete your previous docker container from Docker.

Then re-run:

docker-compose up --build

Enjoy"

**Comment by Lufffya** [comment]
@MatheusMeM @fcodag My system is Ubuntu server 22.04

**Comment by fcodag** [comment]
> @MatheusMeM @fcodag My system is Ubuntu server 22.04, so it does‘t work #160

Check #165, there's more to it and it worked for me (though I'm running it on Win11):
1 - If you're using the free Pinecone teer, you need to update the index name on superagi/jobs/agent_executor/py to your own index name
2 - Looks like GPT-4 is not supported yet. Try 3.5-turbo, that fixed the endless "thinking" state

The performance is still not great, though. I tried getting the current weather conditions and it went on an endless loop trying LlmThinkingTool, which kept responding it can't access internet.

The concept is great, but it's still a bit early. One thing I'm missing is the ability to configure the agent with temperature, max length, top P, freq penalty, etc as well as prompt templates. I'm sure this will come in the future. My full support to this initiative!

**Comment by jerome3o** [comment]
I had the same issue and it was because I was running SuperAGI on a different host. In the docker-compose.yml file i noticed this environment variable specified:

```
NEXT_PUBLIC_API_BASE_URL=http://localhost:8001
```
Which I assume tells the frontend where to send api calls. I changed it to use my server's IP and restarted the deployment but I still got the same issue. 

As a quick workaround I ended up using ssh to port forward ports 3000 and 8001 and accessing it via `localhost:3000`. This fixed the issue but it's definitely a janky workaround

ssh command for convenience:
```sh
ssh -L 8001:localhost:8001 -L 3000:localhost:3000 {your remote host}
```

**Comment by coldfusion571** [comment]
I fixed this by editing 'main.py' and adding the actual IP of my server in the CORS middleware config.

`# Configure CORS middleware  
origins = [  
        "http://localhost:3001",
    "http://localhost:3000",  
    "http://192.168.2.36:3001",  
    "http://192.168.2.36:3000",  
    # Add more origins if needed  
]`

Seems to work.. at least I'm not getting the CORS errors and my tools select is populated so far.

Sorry formatting is crap, I tried.  Make it easier github.

**Comment by neelayan7** [comment]
We have fixed this issue in the newer version releases. Thus closing this.
