### ISSUE TITLE
Delete Agent

### ISSUE THREAD

**Issue by jeffreyha-dev** [TransformerOptimus/SuperAGI#217]
I maybe missing something, how do I delete a created agent? I only see "resume" with the 3 dots. Thanks in advance.

**Comment by klazu456** [comment]
The problem I have now, is that agents are running in the background even if they have been stopped. I would like to just delete the agent completely. Is there a way to do that in the code?

**Comment by bilskirnir** [comment]
> The problem I have now, is that agents are running in the background even if they have been stopped. I would like to just delete the agent completely. Is there a way to do that in the code?

I had the same problem, it was running up my api credits. I just deleted it and I'm going to wait for a future update. It's strange you can't delete them, you would think that was a basic feature.

**Comment by kainnov** [comment]
Anyone try this?
To delete agents from Superagi, you can follow these steps:

Log in to your Superagi account and go to the "Agents" section.
Find the agent you want to delete and click on their name to open their profile page.
Click on the "Delete" button on the top right corner of the page.
Confirm the deletion by clicking on the "Delete" button again on the pop-up message.
It's important to note that deleting an agent will permanently remove them from your account, and you won't be able to restore their information or activity history. So make sure you really want to delete the agent before proceeding.

In case you want to deactivate an agent temporarily instead of deleting them, you can do so by clicking on the gear icon that appears next to their name in the "Agents" section and choosing the "Deactivate" option. This will hide the agent from your dashboard but keep their data stored in your account.

**Comment by JohnHunt999** [comment]
Change done in v0.0.9. Closing this.
