### ISSUE TITLE
error message when running docker compose up --build

### ISSUE THREAD

**Issue by didisoft69** [TransformerOptimus/SuperAGI#507]
=> ERROR [celery 3/8] RUN pip install --upgrade pip. How to fix this?

**Comment by namansleeps** [comment]
Use this command to run a shell in a container 
- docker exec -it { celery container id} bash 
Now run 
- pip install --upgrade pip

it should work now

**Comment by neelayan7** [comment]
@didisoft69 is this issue resolved?

**Comment by didisoft69** [comment]
another problem "=> ERROR [gui deps 4/4] RUN npm ci "

**Comment by markharley12** [comment]
I had an error message running docker compose up --build (os: ubuntu) which was caused by having python3-dev and python:3.10-slim-bullseye.

I removed python3-dev from the dockerfile and it has fixed the problem for me. Unless I am missing something -  the base image python:3.10-slim-bullseye already contains the necessary Python development tools, making the explicit installation of python3-dev redundant and error-prone?

I've made a PR of the exact change that fixed it for me but I am inexperienced so please let me know if I am missing something silly.
